# Generated by Django 2.2.16 on 2022-02-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-MAIL')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='username')),
            ],
            options={
                'verbose_name': 'предпользователь',
                'verbose_name_plural': 'предпользователи',
            },
        ),
    ]
